<?php

use Konanyhin\Envelope\Envelope;
use Konanyhin\Envelope\Helpers\Body;
use Konanyhin\Envelope\Helpers\Head;

it('can create envelope with all components and attributes', function (): void {
    $envelope = Envelope::new([
        'owa' => 'desktop',
        'lang' => 'en',
        'dir' => 'ltr',
    ]);

    $envelope->head(
        Head::title('All Components Test'),
        Head::preview('This is a preview'),
        Head::breakpoint(['width' => '480px']),
        Head::font(['name' => 'Roboto', 'href' => 'https://fonts.googleapis.com/css?family=Roboto']),
        Head::style('.custom-class { color: red; }', ['inline' => 'inline']),
        Head::attributes()
            ->addAll(['font-family' => 'Arial'])
            ->addClass('my-class', ['color' => 'blue'])
            ->add('mj-text', ['font-size' => '14px'])
    );

    $envelope->body(
        Body::wrapper([
            'background-color' => '#ffffff',
            'background-position' => 'top center',
            'background-position-x' => 'center',
            'background-position-y' => 'center',
            'background-repeat' => 'no-repeat',
            'background-size' => 'cover',
            'background-url' => 'https://example.com/bg.jpg',
            'border' => '1px solid #000000',
            'border-bottom' => '1px solid #000000',
            'border-left' => '1px solid #000000',
            'border-radius' => '4px',
            'border-right' => '1px solid #000000',
            'border-top' => '1px solid #000000',
            'css-class' => 'my-wrapper',
            'full-width' => 'full-width',
            'gap' => '0px',
            'padding' => '20px',
            'padding-bottom' => '20px',
            'padding-left' => '20px',
            'padding-right' => '20px',
            'padding-top' => '20px',
            'text-align' => 'center',
        ])->add(
            Body::section([
                'background-color' => '#f0f0f0',
                'background-position' => 'center',
                'background-position-x' => 'center',
                'background-position-y' => 'center',
                'background-repeat' => 'repeat',
                'background-size' => 'auto',
                'background-url' => 'https://example.com/section-bg.jpg',
                'border' => 'none',
                'border-bottom' => 'none',
                'border-left' => 'none',
                'border-radius' => '0',
                'border-right' => 'none',
                'border-top' => 'none',
                'css-class' => 'my-section',
                'direction' => 'ltr',
                'full-width' => 'full-width',
                'padding' => '10px',
                'padding-bottom' => '10px',
                'padding-left' => '10px',
                'padding-right' => '10px',
                'padding-top' => '10px',
                'text-align' => 'left',
            ])->add(
                Body::column([
                    'background-color' => '#ffffff',
                    'border' => '1px solid #eeeeee',
                    'border-bottom' => '1px solid #eeeeee',
                    'border-left' => '1px solid #eeeeee',
                    'border-radius' => '2px',
                    'border-right' => '1px solid #eeeeee',
                    'border-top' => '1px solid #eeeeee',
                    'css-class' => 'my-column',
                    'inner-background-color' => '#fafafa',
                    'inner-border' => '1px dashed #cccccc',
                    'inner-border-bottom' => '1px dashed #cccccc',
                    'inner-border-left' => '1px dashed #cccccc',
                    'inner-border-radius' => '2px',
                    'inner-border-right' => '1px dashed #cccccc',
                    'inner-border-top' => '1px dashed #cccccc',
                    'padding' => '5px',
                    'padding-bottom' => '5px',
                    'padding-left' => '5px',
                    'padding-right' => '5px',
                    'padding-top' => '5px',
                    'vertical-align' => 'middle',
                    'width' => '50%',
                ])->add(
                    Body::text('Hello World', [
                        'align' => 'center',
                        'color' => '#333333',
                        'container-background-color' => '#ffffff',
                        'css-class' => 'my-text',
                        'font-family' => 'Helvetica',
                        'font-size' => '16px',
                        'font-style' => 'italic',
                        'font-weight' => 'bold',
                        'height' => '20px',
                        'letter-spacing' => '1px',
                        'line-height' => '24px',
                        'padding' => '10px',
                        'padding-bottom' => '10px',
                        'padding-left' => '10px',
                        'padding-right' => '10px',
                        'padding-top' => '10px',
                        'text-decoration' => 'underline',
                        'text-transform' => 'uppercase',
                    ]),
                    Body::button('Click Me', [
                        'align' => 'center',
                        'background-color' => '#414141',
                        'border' => 'none',
                        'border-bottom' => 'none',
                        'border-left' => 'none',
                        'border-radius' => '3px',
                        'border-right' => 'none',
                        'border-top' => 'none',
                        'color' => '#ffffff',
                        'container-background-color' => '#ffffff',
                        'css-class' => 'my-button',
                        'font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                        'font-size' => '13px',
                        'font-style' => 'normal',
                        'font-weight' => 'normal',
                        'height' => '40px',
                        'href' => 'https://example.com',
                        'inner-padding' => '10px 25px',
                        'letter-spacing' => '0px',
                        'line-height' => '120%',
                        'padding' => '10px 25px',
                        'padding-bottom' => '10px',
                        'padding-left' => '25px',
                        'padding-right' => '25px',
                        'padding-top' => '10px',
                        'rel' => 'nofollow',
                        'target' => '_blank',
                        'text-align' => 'center',
                        'text-decoration' => 'none',
                        'text-transform' => 'none',
                        'title' => 'Button Title',
                        'vertical-align' => 'middle',
                        'width' => '160px',
                    ]),
                    Body::image([
                        'align' => 'center',
                        'alt' => 'Image Alt',
                        'border' => '0',
                        'border-bottom' => '0',
                        'border-left' => '0',
                        'border-radius' => '0',
                        'border-right' => '0',
                        'border-top' => '0',
                        'container-background-color' => 'transparent',
                        'css-class' => 'my-image',
                        'fluid-on-mobile' => 'true',
                        'height' => 'auto',
                        'href' => 'https://example.com',
                        'name' => 'image-name',
                        'padding' => '10px 25px',
                        'padding-bottom' => '10px',
                        'padding-left' => '25px',
                        'padding-right' => '25px',
                        'padding-top' => '10px',
                        'rel' => 'nofollow',
                        'sizes' => '(max-width: 480px) 100vw, 480px',
                        'src' => 'https://example.com/image.jpg',
                        'srcset' => 'https://example.com/image.jpg 1x',
                        'target' => '_blank',
                        'title' => 'Image Title',
                        'usemap' => '#image-map',
                        'width' => '200px',
                    ]),
                    Body::divider([
                        'align' => 'center',
                        'border-color' => '#cccccc',
                        'border-style' => 'solid',
                        'border-width' => '1px',
                        'container-background-color' => '#ffffff',
                        'css-class' => 'my-divider',
                        'padding' => '10px 25px',
                        'padding-bottom' => '10px',
                        'padding-left' => '25px',
                        'padding-right' => '25px',
                        'padding-top' => '10px',
                        'width' => '100%',
                    ]),
                    Body::spacer([
                        'container-background-color' => '#ffffff',
                        'css-class' => 'my-spacer',
                        'height' => '20px',
                        'padding' => '0',
                        'padding-bottom' => '0',
                        'padding-left' => '0',
                        'padding-right' => '0',
                        'padding-top' => '0',
                    ]),
                    Body::table('<tr><td>Content</td></tr>', [
                        'align' => 'left',
                        'border' => '1px solid #000000',
                        'cellpadding' => '0',
                        'cellspacing' => '0',
                        'color' => '#000000',
                        'container-background-color' => '#ffffff',
                        'css-class' => 'my-table',
                        'font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                        'font-size' => '13px',
                        'line-height' => '22px',
                        'padding' => '10px 25px',
                        'padding-bottom' => '10px',
                        'padding-left' => '25px',
                        'padding-right' => '25px',
                        'padding-top' => '10px',
                        'role' => 'presentation',
                        'table-layout' => 'auto',
                        'width' => '100%',
                    ]),
                    Body::raw('<div>Raw Content</div>'),
                    Body::accordion([
                        'border' => 'none',
                        'container-background-color' => '#ffffff',
                        'css-class' => 'my-accordion',
                        'font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                        'icon-align' => 'middle',
                        'icon-height' => '32px',
                        'icon-position' => 'right',
                        'icon-unwrapped-alt' => '-',
                        'icon-unwrapped-url' => 'https://example.com/minus.png',
                        'icon-width' => '32px',
                        'icon-wrapped-alt' => '+',
                        'icon-wrapped-url' => 'https://example.com/plus.png',
                        'padding' => '10px 25px',
                        'padding-bottom' => '10px',
                        'padding-left' => '25px',
                        'padding-right' => '25px',
                        'padding-top' => '10px',
                    ])->add(
                        Body::accordionElement([
                            'background-color' => '#ffffff',
                            'border' => '1px solid #e0e0e0',
                            'css-class' => 'my-accordion-element',
                            'font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                            'icon-align' => 'middle',
                            'icon-height' => '32px',
                            'icon-position' => 'right',
                            'icon-unwrapped-alt' => '-',
                            'icon-unwrapped-url' => 'https://example.com/minus.png',
                            'icon-width' => '32px',
                            'icon-wrapped-alt' => '+',
                            'icon-wrapped-url' => 'https://example.com/plus.png',
                        ])->withTitle('Accordion Title', [
                            'background-color' => '#ffffff',
                            'color' => '#333333',
                            'font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                            'font-size' => '13px',
                            'font-weight' => 'bold',
                            'padding' => '16px',
                            'padding-bottom' => '16px',
                            'padding-left' => '16px',
                            'padding-right' => '16px',
                            'padding-top' => '16px',
                        ])->withText('Accordion Content', [
                            'background-color' => '#ffffff',
                            'color' => '#333333',
                            'font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                            'font-size' => '13px',
                            'font-weight' => 'normal',
                            'letter-spacing' => '1px',
                            'line-height' => '1',
                            'padding' => '16px',
                            'padding-bottom' => '16px',
                            'padding-left' => '16px',
                            'padding-right' => '16px',
                            'padding-top' => '16px',
                        ])
                    ),
                    Body::carousel([
                        'align' => 'center',
                        'border-radius' => '0',
                        'container-background-color' => '#ffffff',
                        'css-class' => 'my-carousel',
                        'icon-width' => '44px',
                        'left-icon' => 'https://example.com/left.png',
                        'right-icon' => 'https://example.com/right.png',
                        'tb-border' => '2px solid transparent',
                        'tb-border-radius' => '6px',
                        'tb-hover-border-color' => '#fead0d',
                        'tb-selected-border-color' => '#cccccc',
                        'tb-width' => '20px',
                        'thumbnails' => 'visible',
                    ])->add(
                        Body::carouselImage([
                            'alt' => 'Carousel Image',
                            'css-class' => 'my-carousel-image',
                            'href' => 'https://example.com',
                            'rel' => 'nofollow',
                            'src' => 'https://example.com/carousel.jpg',
                            'target' => '_blank',
                            'thumbnails-src' => 'https://example.com/carousel-thumb.jpg',
                            'title' => 'Carousel Image Title',
                        ])
                    ),
                    Body::navbar([
                        'align' => 'center',
                        'base-url' => 'https://example.com',
                        'css-class' => 'my-navbar',
                        'hamburger' => 'hamburger',
                        'ico-align' => 'center',
                        'ico-close' => '&#8855;',
                        'ico-color' => '#444444',
                        'ico-font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                        'ico-font-size' => '44px',
                        'ico-line-height' => '44px',
                        'ico-open' => '&#9776;',
                        'ico-padding' => '10px',
                        'ico-padding-bottom' => '10px',
                        'ico-padding-left' => '10px',
                        'ico-padding-right' => '10px',
                        'ico-padding-top' => '10px',
                        'ico-text-decoration' => 'none',
                        'ico-text-transform' => 'uppercase',
                    ])->add(
                        Body::navbarLink('Home', [
                            'color' => '#000000',
                            'css-class' => 'my-navbar-link',
                            'font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                            'font-size' => '13px',
                            'font-style' => 'normal',
                            'font-weight' => 'normal',
                            'href' => '/home',
                            'letter-spacing' => '2px',
                            'line-height' => '22px',
                            'padding' => '15px 10px',
                            'padding-bottom' => '15px',
                            'padding-left' => '10px',
                            'padding-right' => '10px',
                            'padding-top' => '15px',
                            'rel' => 'nofollow',
                            'target' => '_blank',
                            'text-decoration' => 'none',
                            'text-transform' => 'uppercase',
                        ])
                    ),
                    Body::social([
                        'align' => 'center',
                        'border-radius' => '3px',
                        'color' => '#333333',
                        'container-background-color' => '#ffffff',
                        'css-class' => 'my-social',
                        'font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                        'font-size' => '13px',
                        'font-style' => 'normal',
                        'font-weight' => 'normal',
                        'icon-height' => '20px',
                        'icon-size' => '20px',
                        'inner-padding' => '4px',
                        'line-height' => '22px',
                        'mode' => 'horizontal',
                        'padding' => '10px 25px',
                        'padding-bottom' => '10px',
                        'padding-left' => '25px',
                        'padding-right' => '25px',
                        'padding-top' => '10px',
                        'icon-padding' => '0px',
                        'text-padding' => '4px 4px 4px 0',
                        'text-decoration' => 'none',
                    ])->add(
                        Body::socialElement('Facebook', [
                            'align' => 'center',
                            'alt' => 'Facebook',
                            'background-color' => '#3b5998',
                            'border-radius' => '3px',
                            'color' => '#ffffff',
                            'css-class' => 'my-social-element',
                            'font-family' => 'Ubuntu, Helvetica, Arial, sans-serif',
                            'font-size' => '13px',
                            'font-style' => 'normal',
                            'font-weight' => 'normal',
                            'href' => 'https://facebook.com',
                            'icon-height' => '20px',
                            'icon-size' => '20px',
                            'line-height' => '22px',
                            'name' => 'facebook',
                            'padding' => '4px',
                            'padding-bottom' => '4px',
                            'padding-left' => '4px',
                            'padding-right' => '4px',
                            'padding-top' => '4px',
                            'icon-padding' => '0px',
                            'icon-position' => 'left',
                            'text-padding' => '4px 4px 4px 0',
                            'sizes' => '(max-width: 480px) 100vw, 480px',
                            'src' => 'https://example.com/facebook.png',
                            'srcset' => 'https://example.com/facebook.png 1x',
                            'rel' => 'nofollow',
                            'target' => '_blank',
                            'title' => 'Facebook',
                            'text-decoration' => 'none',
                            'vertical-align' => 'middle',
                        ])
                    )
                )
            )
        )
    );

    $envelope->body(
        Body::hero([
            'background-color' => '#ffffff',
            'background-height' => '256px',
            'background-position' => 'center center',
            'background-url' => 'https://example.com/hero.jpg',
            'background-width' => '600px',
            'border-radius' => '0px',
            'height' => '256px',
            'mode' => 'fluid-height',
            'padding' => '100px 0px',
            'padding-bottom' => '100px',
            'padding-left' => '0px',
            'padding-right' => '0px',
            'padding-top' => '100px',
            'vertical-align' => 'top',
        ])->add(
            Body::text('Hero Text')
        )
    );

    $envelope->body(
        Body::section()->add(
            Body::group([
                'background-color' => '#ffffff',
                'direction' => 'ltr',
                'vertical-align' => 'top',
                'width' => '100%',
                'css-class' => 'my-group',
            ])
        )
    );

    $envelope->getBody()->setAttributes([
        'background-color' => '#ffffff',
        'css-class' => 'my-body',
        'width' => '1000px',
    ]);

    $result = $envelope->convert();

    expect($result->errors())->toBeArray()->toBeEmpty()
        ->and($result->html())->toBeString()->not->toBeEmpty();
});
